//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace Resmed.Stock.Core
{
    public partial class StockEntities : ObjectContext
    {
        public const string ConnectionString = "name=StockEntities";
        public const string ContainerName = "StockEntities";
    
        #region Constructors
    
        public StockEntities()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        public StockEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public StockEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // Creating proxies requires the use of the ProxyDataContractResolver and
            // may allow lazy loading which can expand the loaded graph during serialization.
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<StockSymbol> StockSymbols
        {
            get { return _stockSymbols  ?? (_stockSymbols = CreateObjectSet<StockSymbol>("StockSymbols")); }
        }
        private ObjectSet<StockSymbol> _stockSymbols;
    
        public ObjectSet<Site> Sites
        {
            get { return _sites  ?? (_sites = CreateObjectSet<Site>("Sites")); }
        }
        private ObjectSet<Site> _sites;
    
        public ObjectSet<StockFile> StockFiles
        {
            get { return _stockFiles  ?? (_stockFiles = CreateObjectSet<StockFile>("StockFiles")); }
        }
        private ObjectSet<StockFile> _stockFiles;

        #endregion

    }
}
